TRANSLATIONS = {
    "en": {
        # Page
        "title":         "🌾 Kisan Mitra | किसान मित्र",
        # Results
        "best_crop":     "Best Crop for Your Farm",
        "fertilizer":    "Fertilizer Recommendation",
        "tip":           "Farming Tip",
        "confidence":    "Confidence",
        "alt_crops":     "Alternative Crops",
        # Section headers
        "enter_farm":    "Enter Farm Details",
        "soil":          "Soil",
        "weather":       "Weather",
        "location":      "Location",
        # Soil inputs
        "soil_type":     "Soil Type",
        "loamy":         "Loamy",
        "sandy":         "Sandy",
        "clay":          "Clay",
        "nitrogen":      "Nitrogen (N)",
        "phosphorus":    "Phosphorus (P)",
        "potassium":     "Potassium (K)",
        "soil_ph":       "Soil pH",
        # Weather inputs
        "temperature":   "Temperature (°C)",
        "humidity":      "Humidity (%)",
        "rainfall":      "Rainfall (mm)",
        # Location inputs
        "state":         "State",
        "state_info":    "State-specific pricing & scheme data coming soon.",
        # Weather sidebar
        "live_weather":  "🌤 Live Weather",
        "enter_city":    "Enter city",
        "fetch_weather": "Fetch Weather",
        "temp_label":    "🌡 Temperature (°C)",
        "humid_label":   "💧 Humidity (%)",
        # Button
        "predict_btn":   "🔍 Get Crop Recommendation",
        "analysing":     "Analysing your farm data...",
        # Charts
        "chart_conf":    "📊 Prediction Confidence",
        "chart_soil":    "🧪 Soil Nutrient Profile",
        "train_hint":    "💡 Run `python scripts/train_model.py` from the project root to train the model first.",
    },
    "hi": {
        "title":         "🌾 किसान मित्र",
        "best_crop":     "आपके खेत के लिए सर्वोत्तम फसल",
        "fertilizer":    "उर्वरक अनुशंसा",
        "tip":           "खेती की सलाह",
        "confidence":    "विश्वसनीयता",
        "alt_crops":     "वैकल्पिक फसलें",
        "enter_farm":    "खेत की जानकारी दर्ज करें",
        "soil":          "मिट्टी",
        "weather":       "मौसम",
        "location":      "स्थान",
        "soil_type":     "मिट्टी का प्रकार",
        "loamy":         "दोमट",
        "sandy":         "रेतीली",
        "clay":          "चिकनी मिट्टी",
        "nitrogen":      "नाइट्रोजन (N)",
        "phosphorus":    "फॉस्फोरस (P)",
        "potassium":     "पोटेशियम (K)",
        "soil_ph":       "मिट्टी pH",
        "temperature":   "तापमान (°C)",
        "humidity":      "आर्द्रता (%)",
        "rainfall":      "वर्षा (mm)",
        "state":         "राज्य",
        "state_info":    "राज्य-विशिष्ट मूल्य और योजना डेटा जल्द आ रहा है।",
        "live_weather":  "🌤 लाइव मौसम",
        "enter_city":    "शहर दर्ज करें",
        "fetch_weather": "मौसम देखें",
        "temp_label":    "🌡 तापमान (°C)",
        "humid_label":   "💧 आर्द्रता (%)",
        "predict_btn":   "🔍 फसल सिफारिश पाएं",
        "analysing":     "आपके खेत का विश्लेषण हो रहा है...",
        "chart_conf":    "📊 अनुमान विश्वसनीयता",
        "chart_soil":    "🧪 मिट्टी पोषक तत्व प्रोफ़ाइल",
        "train_hint":    "💡 मॉडल प्रशिक्षित करने के लिए `python scripts/train_model.py` चलाएं।",
    },
    "mr": {
        "title":         "🌾 किसान मित्र",
        "best_crop":     "तुमच्या शेतासाठी सर्वोत्तम पीक",
        "fertilizer":    "खत शिफारस",
        "tip":           "शेती टिप्स",
        "confidence":    "विश्वासार्हता",
        "alt_crops":     "पर्यायी पिके",
        "enter_farm":    "शेताचा तपशील भरा",
        "soil":          "माती",
        "weather":       "हवामान",
        "location":      "स्थान",
        "soil_type":     "मातीचा प्रकार",
        "loamy":         "चिकणमाती",
        "sandy":         "वाळूमाती",
        "clay":          "गाळमाती",
        "nitrogen":      "नायट्रोजन (N)",
        "phosphorus":    "स्फुरद (P)",
        "potassium":     "पालाश (K)",
        "soil_ph":       "मातीचा pH",
        "temperature":   "तापमान (°C)",
        "humidity":      "आर्द्रता (%)",
        "rainfall":      "पाऊस (mm)",
        "state":         "राज्य",
        "state_info":    "राज्य-विशिष्ट किंमत व योजना लवकरच येत आहे.",
        "live_weather":  "🌤 थेट हवामान",
        "enter_city":    "शहर टाका",
        "fetch_weather": "हवामान पहा",
        "temp_label":    "🌡 तापमान (°C)",
        "humid_label":   "💧 आर्द्रता (%)",
        "predict_btn":   "🔍 पीक शिफारस मिळवा",
        "analysing":     "तुमच्या शेताचे विश्लेषण होत आहे...",
        "chart_conf":    "📊 अंदाज विश्वासार्हता",
        "chart_soil":    "🧪 माती पोषक तत्त्व प्रोफाइल",
        "train_hint":    "💡 मॉडल प्रशिक्षित करण्यासाठी `python scripts/train_model.py` चालवा.",
    },
}

def t(key: str, lang: str = "en") -> str:
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, TRANSLATIONS["en"].get(key, key))
